_include_yml: velox

featurization:
  training_split: train
  used_method: word2vec
  emb_dim: 128

feat_inference:
  preserve_event_keys: True

batching:
  node_features: node_emb
  intra_graph_batching:
    used_methods: edges
    edges:
      intra_graph_batch_size: 1024

training:
  lr: 0.0001
  node_hid_dim: 128
  node_out_dim: 128
  encoder:
    used_methods: vigil
    dropout: 0.3
    vigil:
      num_residual_blocks: 2
  decoder:
    used_methods: predict_edge_type

evaluation:
  node_evaluation:
    threshold_method: max_val_loss
    use_kmeans: False

postprocessing:
  incidents:
    enabled: True
